spring.application.name=katabooks

spring.datasource.url=jdbc:postgresql://localhost:5433/katabooks

# Les identifiants définis dans le docker-compose
spring.datasource.username=postgres
spring.datasource.password=postgres

# Le pilote (driver) pour que Java sache parler à PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# créer ou mettre à jour automatiquement les tables dans PostgreSQL !
spring.jpa.hibernate.ddl-auto=update

# Permet d'afficher les requêtes SQL générées dans la console (très utile pour débugger et apprendre)
spring.jpa.show-sql=true

# Formate le SQL dans la console pour qu'il soit lisible
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


